// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/wal.proto

package wal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	OldFiles      []string               `protobuf:"bytes,3,rep,name=old_files,json=oldFiles,proto3" json:"old_files,omitempty"`
	CompactedFile string                 `protobuf:"bytes,4,opt,name=compacted_file,json=compactedFile,proto3" json:"compacted_file,omitempty"`
	NewLevel      uint32                 `protobuf:"varint,5,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogRecord) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *LogRecord) GetOldFiles() []string {
	if x != nil {
		return x.OldFiles
	}
	return nil
}

func (x *LogRecord) GetCompactedFile() string {
	if x != nil {
		return x.CompactedFile
	}
	return ""
}

func (x *LogRecord) GetNewLevel() uint32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *LogRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LogRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_wal_proto protoreflect.FileDescriptor

const file_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/wal.proto\x12\x03wal\"\xc6\x01\n" +
	"\tLogRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1b\n" +
	"\told_files\x18\x03 \x03(\tR\boldFiles\x12%\n" +
	"\x0ecompacted_file\x18\x04 \x01(\tR\rcompactedFile\x12\x1b\n" +
	"\tnew_level\x18\x05 \x01(\rR\bnewLevel\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestampB0Z.github.com/marcopiovanello/hookdb/internal/walb\x06proto3"

var (
	file_proto_wal_proto_rawDescOnce sync.Once
	file_proto_wal_proto_rawDescData []byte
)

func file_proto_wal_proto_rawDescGZIP() []byte {
	file_proto_wal_proto_rawDescOnce.Do(func() {
		file_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)))
	})
	return file_proto_wal_proto_rawDescData
}

var file_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_wal_proto_goTypes = []any{
	(*LogRecord)(nil), // 0: wal.LogRecord
}
var file_proto_wal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wal_proto_init() }
func file_proto_wal_proto_init() {
	if File_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wal_proto_rawDesc), len(file_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wal_proto_goTypes,
		DependencyIndexes: file_proto_wal_proto_depIdxs,
		MessageInfos:      file_proto_wal_proto_msgTypes,
	}.Build()
	File_proto_wal_proto = out.File
	file_proto_wal_proto_goTypes = nil
	file_proto_wal_proto_depIdxs = nil
}
